apiVersion: citrix.citrix.com/v1alpha1
kind: Citrix-adc-istio-ingress-gateway
metadata:
  name: citrix-adc-istio-ingress-gateway-sample
spec:
  # Default values copied from <project_dir>/helm-charts/citrix-adc-istio-ingress-gateway/values.yaml
  ADMSettings:
    ADMIP: null
    bandWidth: null
    bandWidthLicense: false
    cpxCores: null
    licenseServerIP: null
    licenseServerPort: 27000
    vCPULicense: false
  certProvider:
    caAddr: istiod.istio-system.svc
    caPort: 15012
    certTTLinHours: 720
    clusterId: Kubernetes
    jwtPolicy: null
    trustDomain: cluster.local
  citrixCPX: false
  coe:
    coeTracing: false
    coeURL: null
  ingressGateway:
    EULA: false
    adcServerName: null
    httpNodePort: 30180
    httpsNodePort: 31443
    image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-79.64
    imagePullPolicy: IfNotPresent
    label: citrix-ingressgateway
    lightWeightCPX: 1
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    multiClusterIngress: false
    multiClusterListenerNodePort: 32443
    multiClusterListenerPort: 15443
    multiClusterSvcDomain: global
    netProfile: null
    netscalerUrl: null
    nodePortRequired: false
    secretVolumes: null
    tcpPort: null
    vserverIP: nsip
  istioPilot:
    SAN: null
    insecureGrpcPort: 15010
    name: istiod
    namespace: istio-system
    secureGrpcPort: 15012
  metricExporter:
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.8
    imagePullPolicy: IfNotPresent
    logLevel: ERROR
    port: 8888
    required: true
    secure: "YES"
  secretName: nslogin
  xDSAdaptor:
    image: quay.io/citrix/citrix-xds-adaptor:0.9.9
    imagePullPolicy: IfNotPresent
    jsonLog: false
    logLevel: DEBUG
    proxyType: router
    secureConnect: true
  
  
