apiVersion: citrix.citrix.com/v1alpha1
kind: Citrix-cpx-istio-sidecar-injector
metadata:
  name: citrix-cpx-istio-sidecar-injector-sample
spec:
  # Default values copied from <project_dir>/helm-charts/citrix-cpx-istio-sidecar-injector/values.yaml
  ADMSettings:
    ADMFingerPrint: null
    ADMIP: null
    bandWidth: null
    bandWidthLicense: false
    licenseServerIP: null
    licenseServerPort: 27000
  certProvider:
    caAddr: istiod-basic.istio-system.svc
    caPort: 15012
    certTTLinHours: 720
    clusterId: Kubernetes
    trustDomain: cluster.local
  coe:
    coeURL: null
  cpxProxy:
    EULA: false
    cpxSidecarMode: true
    image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-58.30
    imagePullPolicy: IfNotPresent
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    netscalerUrl: http://127.0.0.1
  istioPilot:
    SAN: null
    insecureGrpcPort: 15010
    name: istiod-basic
    namespace: istio-system
    secureGrpcPort: 15012
  sidecarWebHook:
    imagePullPolicy: IfNotPresent
    webhookImage: gcr.io/istio-release/sidecar_injector:1.0.0
  webhook:
    injectionLabelName: cpx-injection
  xDSAdaptor:
    image: quay.io/citrix/citrix-xds-adaptor:0.9.5
    imagePullPolicy: IfNotPresent
    proxyType: sidecar
    secureConnect: true
  
  
