# permissions for end users to view citrix-adc-istio-ingress-gateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: citrix-adc-istio-ingress-gateway-viewer-role
rules:
- apiGroups:
  - citrix.citrix.com
  resources:
  - citrix-adc-istio-ingress-gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - citrix.citrix.com
  resources:
  - citrix-adc-istio-ingress-gateways/status
  verbs:
  - get
