apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "citrix.citrix.com/v1alpha1",
          "kind": "Citrix-adc-istio-ingress-gateway",
          "metadata": {
            "name": "citrix-adc-istio-ingress-gateway-sample"
          },
          "spec": {
            "ADMSettings": {
              "ADMFingerPrint": "",
              "ADMIP": "",
              "bandWidth": "",
              "bandWidthLicense": false,
              "cpxCores": "",
              "licenseServerIP": "",
              "licenseServerPort": 27000,
              "vCPULicense": false
            },
            "certProvider": {
              "caAddr": "istiod-basic.istio-system.svc",
              "caPort": 15012,
              "certTTLinHours": 720,
              "clusterId": "Kubernetes",
              "trustDomain": "cluster.local"
            },
            "citrixCPX": false,
            "coe": {
              "coeURL": ""
            },
            "ingressGateway": {
              "EULA": false,
              "adcServerName": "",
              "exposeMutipleApps": false,
              "exposeNonHttpService": false,
              "httpNodePort": 30180,
              "httpsNodePort": 31443,
              "image": "quay.io/citrix/citrix-k8s-cpx-ingress:13.0-58.30",
              "imagePullPolicy": "IfNotPresent",
              "label": "citrix-ingressgateway",
              "lightWeightCPX": 1,
              "mgmtHttpPort": 10080,
              "mgmtHttpsPort": 10443,
              "netProfile": "",
              "netscalerUrl": "",
              "secretVolumes": {
                "mountPath": "",
                "name": "",
                "secretName": ""
              },
              "tcpPort": {
                "name": "",
                "nodePort": "",
                "port": "",
                "targetPort": ""
              },
              "vserverIP": "nsip"
            },
            "istioPilot": {
              "SAN": "",
              "insecureGrpcPort": 15010,
              "name": "istiod-basic",
              "namespace": "istio-system",
              "secureGrpcPort": 15012
            },
            "metricExporter": {
              "image": "quay.io/citrix/citrix-adc-metrics-exporter:1.4.6",
              "imagePullPolicy": "IfNotPresent",
              "logLevel": "ERROR",
              "port": 8888,
              "required": true,
              "secure": "YES"
            },
            "xDSAdaptor": {
              "image": "quay.io/citrix/citrix-xds-adaptor:0.9.5",
              "imagePullPolicy": "IfNotPresent",
              "proxyType": "router",
              "secureConnect": true
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: "Networking"
    description: An Istio ingress gateway acts as an entry point for the incoming traffic and secures and controls access to the service mesh from outside. It also performs routing and load balancing. Citrix ADC CPX, MPX, or VPX can be deployed as an ingress gateway to the Istio service mesh.
    containerImage: registry.connect.redhat.com/citrix/istioingressgateway:v0.9.5-v1beta
    createdAt: 2021-01-06T14:16:17Z
    support: citrix-adc-istio-ingress-gateway-operator
    repository: https://github.com/citrix/citrix-xds-adaptor
    operators.operatorframework.io/builder: operator-sdk-v1.3.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: citrix-adc-istio-ingress-gateway-operator.v0.9.5
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Citrix-adc-istio-ingress-gateway
      name: citrix-adc-istio-ingress-gateways.citrix.citrix.com
      version: v1alpha1
  description: An Istio ingress gateway acts as an entry point for the incoming traffic and secures and controls access to the service mesh from outside. It also performs routing and load balancing. Citrix ADC CPX, MPX, or VPX can be deployed as an ingress gateway to the Istio service mesh.
  displayName: Citrix ADC Istio Ingress Gateway Operator
  icon:
  - base64data: "/9j/4AAQSkZJRgABAQAAAQABAAD/4gKgSUNDX1BST0ZJTEUAAQEAAAKQbGNtcwQwAABtbnRyUkdCIFhZWiAAAAAAAAAAAAAAAABhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtkZXNjAAABCAAAADhjcHJ0AAABQAAAAE53dHB0AAABkAAAABRjaGFkAAABpAAAACxyWFlaAAAB0AAAABRiWFlaAAAB5AAAABRnWFlaAAAB+AAAABRyVFJDAAACDAAAACBnVFJDAAACLAAAACBiVFJDAAACTAAAACBjaHJtAAACbAAAACRtbHVjAAAAAAAAAAEAAAAMZW5VUwAAABwAAAAcAHMAUgBHAEIAIABiAHUAaQBsAHQALQBpAG4AAG1sdWMAAAAAAAAAAQAAAAxlblVTAAAAMgAAABwATgBvACAAYwBvAHAAeQByAGkAZwBoAHQALAAgAHUAcwBlACAAZgByAGUAZQBsAHkAAAAAWFlaIAAAAAAAAPbWAAEAAAAA0y1zZjMyAAAAAAABDEoAAAXj///zKgAAB5sAAP2H///7ov///aMAAAPYAADAlFhZWiAAAAAAAABvlAAAOO4AAAOQWFlaIAAAAAAAACSdAAAPgwAAtr5YWVogAAAAAAAAYqUAALeQAAAY3nBhcmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbcGFyYQAAAAAAAwAAAAJmZgAA8qcAAA1ZAAAT0AAACltwYXJhAAAAAAADAAAAAmZmAADypwAADVkAABPQAAAKW2Nocm0AAAAAAAMAAAAAo9cAAFR7AABMzQAAmZoAACZmAAAPXP/bAEMABQMEBAQDBQQEBAUFBQYHDAgHBwcHDwsLCQwRDxISEQ8RERMWHBcTFBoVEREYIRgaHR0fHx8TFyIkIh4kHB4fHv/bAEMBBQUFBwYHDggIDh4UERQeHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHv/CABEIAZABkAMBIgACEQEDEQH/xAAbAAEAAwADAQAAAAAAAAAAAAAABAUGAQMHAv/EABoBAQEBAQEBAQAAAAAAAAAAAAACAQQDBQb/2gAMAwEAAhADEAAAAbXg+v8AhgAAAAAAAAAAAAAAAAAAAAAAHPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOKrKtnX2bJWWKvoJAAAAAEFs5CmgMAAAAAAAAAAAAAjef+kxZ6INxxzvj5/tcVtZ6ZYvkAAAAAYjb9OeuR2nT3Ab5AAAAAAAAAI3GIn3ta+8uc9MXZaGhboO7A7qvHsymr8+yt72R5FeGAmQ9L5d9TouudfNT/EKnz2nx9VITT3cXs3ypdRg94qm4scQr0BWWdcwqm9HdltvPRIFcoAAAAAAAGQm53eR2SBfGBkLq1Z6vPfQvPZ9d1IjyL5/P9ritrHTLF8mT7umbHZfi+NAnwMrJbzB7zPdAnq5/P9rEzEdmwxn1qzvmF8YMAAAAAAAA849Dw2sjrsRfIAU0zLm+e+heez77qRHkXz+f7XFbWOmWL5MnNhTY7L8XxoE+BlZLeYPeZ7j5rm+MLJtY7KPc5+vNo45vjAAAAAAAAAoaXb5eOrS9nn9ruauLnalvG2rr5jz30Lz7N3MiPIvn8/2uL2kdMsXyZObCnR2XwvjQZ0HKyO8wm7z34yM6rypOs+fqvDjI6/5MrrMPdT7Xz4q657dCm7gMAAAAAAAiwLll09j3gNhDmGgyHL5NBkf77TQY45EOYNj9nYAYB1fEg11dpnx9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAc8AAAAAAAAAAAAAAAAAAAAAAAA5P/8QAKhAAAgEEAQQBAwQDAAAAAAAAAwQCAAEFNBASEzNAIBEUMBUhMpAiIyT/2gAIAQEAAQUC/vHlkF4yhKM40V0IiRvaVvystCBSzIj+81aV16xNpWWpvZT1fy5K0rN4q0vuvekuGUuG9lPV/KUQyWGOA7escwwxNkiXq7TF6i2xGg5KVqESBYcMPmswOXWOm9kb5oQ/Uj0ka5w5JqYbhf8A+Yrx53s0xakXpzIxPthTdLNiskxMFse53vjkHe1fGsTPD0mTRCIkyHKtjo2tEIo1MIp05j/pZU8gEHK04UxsLa9N7Kya8gfYrVCEYRzPnCORSASCO01wTsBMIiP6iO3TAYnGWE1zIs2PDjINdiABTYKAUQj9LLF6z4gH+Pwya94FxcZxWpjYW16b2U9XjM+fCw/fl/UR2+HF4sDtci5lTxOJtiK4/wDYwZQEQD9M1+oq8egHzY2Ftem9lPV4zPnw3h5f1EdvnIK9+C5prmMSbJkVrAh6l/5j/h82NhbXpvZT1eMz58N4eX9RHb5JOI4Mk751C9g8JRnH1HYdtrHE7ivwfc7Ekz98VMbC2vTeynq8Znz4bw8v6iO3xK9o2faueeMU6bZNSse12ZWva9vTywOuCLH25ISjOPDBoBGWcjFSF2V6Y2Ftem9lPV4zPnw3h5f1EdvjIt92+NU678ZFTtXxrfRf1HUL2uIxQSjkyVPJFvUpFPNBLt8s7C2vTe0pq8ZrzYbw8vaiG3WXPKNIK3PO1rWtxK1pReWuuTEnlOM/r02MWwgEuQnolAItXxy96jjl7UMQx/CawJk4IsEk+TBGWw4RHHm/72EuEUqMEZbQhGEfgSESRCEYrV24fSMYx/u+/8QAJxEAAgIABQQCAgMAAAAAAAAAAQIAAwQQERIxITAyQSIzIHATQmH/2gAIAQMBAT8B/dIUtxkVI5/MAniEEc9+q3ZGbcdZf4D86rNh1lr7zr26qt/Uw2VrwIHrfoRLatkw6g66w8x2UKN0sZCPiIlalBrP5qx0AjbWf4zEKA3SVqrrp7jAqdDFUsdBLVVF2++1adlYGbXFl2zC+4eZf4DI/TknkJifKA6HUQ6XLr7nSlf9hO7r2r+qg5lCF3TC+4eZf4DJvpyTyExPlkiipdTHUWruXt1WAjY0bDn1Fw5/tL7AfiJhfcPMv8Bk305J5CYnylSBRvaWOXOsrsKGXICN6wLrCNOyLGHBhdjzkCRxlqTlqeMySeZqeM9Tx+5//8QAIBEAAgICAwEAAwAAAAAAAAAAAAEQEQJBITAxEiBwgP/aAAgBAgEBPwH+AmrjH82rEq62ymU0J2ZQhWN8lM0Yj4lc9S5c0ZRj7G4ZjHh714zZlGPsbhmMPkXHW1s+j6EjKMY3DMRvQlQ1Ynrror96f//EADEQAAECAwUGBQQDAQAAAAAAAAEAAgMREhAhMUFyICIyQFFxEzBhgaEjM0KRUpCSsf/aAAgBAQAGPwL+8enePqAg5pmDZQaifRTGB86TyZ9Atw39Dzzw3GVm9mbrImpQ9PnOqzwQIwGPP1GG2dsTUoenzpPaCpMaBy83lfTAaF91y+45SitmOoVTDMWuDZUg4JruosiakGCmQ9F+P6VZEig2HdPNVxeKcpDNXGkei+65CHEvnmnP6BBj5EOsaGZ5qiJx/wDdnw4fFmeidXiM+TLz7KZvJVUa89FdDaPZb0Nv6VcH/KqGGYQe3A2P1KHpFkTUmOLLyOq+38qlokE3SgxuJV7andSpGG1VtnP1UTsofeyhykbiMCr+MY20t4z8KQ9ygxvJ0ZNXjOxy2a2N3XKTxK+6x+pQ9IsialD02t0p8T22InZQ+9svyGBXRzVUMcwpnHIL+TnKkY5nlHO6lMb6eQ/UoekWRNSh6bW6U/vsROyh99ipvGPlT/YU8zgFM8Zx5X3Te3kP1KHpFkTUoem1ulP77ETsoffYL3GQCLw2U0HFs0HNMweVePVN6i47IY0AuVcpHOx+pQ9IsialD02t0p/fYidlD72zJkApDgGC8aIL/wAQjGhjUFS7gPwpjlPFbi3FX8JxVTTMW1O9gi44uTW552P1KHpFkTUoem1ulP77ETsofe3w2cA+V4sQbow9bfEYNw/C8KId3I9OVL4Iu6LdcW+i3mNK3WtCvm4rxIvFkOlr9Sh6bImpQ9NrOyfq2InZQ+9ghNunipu4BipDC0tImCruA4Iw3X04FXGRUN5NVRv7KJ/ESp5LfYCvzHuvzPutxgGxW5gnbW5gJ2JPbNUsEhsSKqYyRs+o2apaJDZpeJhSY2VgFIuwVwl/d9//xAApEAEAAgIBAgUFAQEBAQAAAAABABExUSEQUDBBYaHwIHGBscFAkdHh/9oACAEBAAE/IVbeZbuW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu5buW7lu4LZzHL3EyRy9xMkcvcTJHL3EyRy9xMkcvcTJHL3EyRy9xMkcvcTJHL3EyRy9xMkcvcTJHL3EyRy9xMkcvcTJHL3EyRy9xMkcvcTJHL/geJzFR6CG2wk6PaxlHBBL2Fj4yYgvItgLdTOTxTJHL/gyLXURumX+wW/Z098nsXjPNvMvSLvaH8fFMkcv+G+9tUACgoOnvk9i8ahN9ZXa+h4pkjl8Hhf0ebGU3p5Y/b+BiVn5uY4C/MQwf9HWhFS4ZnENVPT3yD7Roj0ZCeUU1KvkLUQR0JogXfZoQv3YQ5gDKbLbgi2pVjHQ7Qb8iZEAw/SSxGRQXlwM+EZI5fA5EdNs5HvoD9Qh9m4IBUgNSIs7WuVfyB1/YIvlhZ096/c+A1098ljsKtp8ShM54CfK9YA9pC9XnBP+IYqUoQxbH0JDUfs6ZzyXYefrK3Qxt+vULAT4/qc1leU8oFdB578IyRy+A1N4/eAIuXH01rHmaMMCq5EOunvX7nwGunvk9i6/K9YKg5OHgZF5cQrvy7khbj/4GMeZ/mgebVBfI/zPhmSOXwFc81hAeR8D3r9z4DXT3yexdfles+b6eDkBRAXH8SpR44bzl9CpReXpONrla9PEMkcvgcUPlCtjzHge9fufAa6e+T2Lr8r1nzfTwsjZBQCygCUyA4ROSG2FY+IZI5fAfyHkfmDzfpZGNFt+U8jBodPev3PgNdPfJ7F1+V6z5vp4GQpMC1ZydMDfrKDkMnl6z2kP3FvVbn+oSSxw+GZI5fAcCvg+yL5rjP8AYbG2E6un/YzkqbEtH1/d096/c+A1098nsXX5XrPm+n1pCgW4iO/Jy7Sp1I+bo8zzlHJtKLkcnhjJHL4CCU4lwR8vnPtGlx5wU/4HEEr1XMuKfiXAh6x7t+5ws0/XTj91PauuV88z5np9HOiBdXQHaBtb9JzCG5b9ITIBwHU4QKSXyzk/yWP0/ggTPXqhIdF+U/8AeoOefrMkcvhZ5N+cc4ftf/ES5/LB9faT6LxX79fUvO4AFGOoMVcQ+U/I+gCBY5IpIvn0HA1xCZzwH0vSv5MRmLnoBwDBqYT4Bxo+syRy9xMkcvcTJHL3EyRy9xMkcvcTJHL3EyRy9xMkcvcTJHL3EyRy9xMkcvcTJHL3EyRy9xMkcvcTJHL3EyRy9xMkcvcTJHL3EyRG3iU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqU6lOpTqA2cT//2gAMAwEAAgADAAAAEOcccccccccccccccccccccccdaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAACiTAAAAAAACAAAAAFaQAAAAQQEi/QAAQAAQaAAAAAFaQAAGo0iAQQvlZ26sCQBAAAAFaQAAXQAYVwPQFQF6USAAQAAAFaQAAeQAB1wPQVAF6QcdQQAAAFaQAAD4FOEwPQXAA4YqsTwiAAFaQAAAMggAAEAEAAYEAAMAQQAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFaQAAAAAAAAAAAAAAAAAAAAAAFbTTTTTTTTTTTTTTTTTTTTTTTXf/xAAjEQACAgEEAgIDAAAAAAAAAAAAARExIRAgQEFx8DChUWGR/9oACAEDAQE/EGySSSSSSSSSSSSSSSSSSSSSSRPI+QrHyFY+QrHyFY+QrHyFY+QrHyFY/grkjUYYmTS972EljWEh7lY/gWrTRM/ke3xvVORjy3Kx7H9BIw8w/wAIY+KY7gkWHQzkkh0DG8n7JFEZSGBChGB3qGiwSARkU7SseyIe9UFlXZYXnt8aO0se50+wirwPVYJCUEpTsPaV7VY9ULG+zqmMsMsLz2+NKfe9PsIq8adi2dyFuVj2dVRN90TpwRC0osLz2+NKfe9PsFXg/kYlImao6VdjlwMaHqrHtxLDGtOmUaNGok3WmLLGrCWkmWWNcWWBNobm9VY+QrHyFY+QrHyFY+QrHyFY+QrHyFY0QQQQQQQQQQQQQQQQQQQQQQQJZP/EAB8RAQACAgMAAwEAAAAAAAAAAAEAERAxITBBIGFwQP/aAAgBAgEBPxD9pUN4EfmtQb/gwUVNn51JU665ZtjyBxEmoagV4gDzEIu9hZyiU5iVcGy4tFxqvq3MhG55hqbMGOk1iXC39Tl/UCurgpml1PMNTZgx0muFeiK9PWw0gPYjyVcs8w1NnBjpNYy0lCUIw2i1BvpQwBhLxWKyFSs1+z//xAApEAABAgQFBAMBAQEAAAAAAAABABEhYZGhEDFBUfAgMFBxgbHB0UDx/9oACAEBAAE/EM5M91MVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVMVUxVTFVnJnur7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7yN8r7/AQAkkACJJRy1kxAP3eyCRR9RgakiwklmXFkA6IA1B7wFTuBmN4kMmFMUIARuznu3yvv8AA66xAMzDJCGAguxB0RSAkCZBGr4cfuuB27wUmECMiyDIbTgIZQMx+W7t8r7/AAuZMuSzGe6ExgGAAYAYcfuuJ27wGHsmRHooiK+Yaf33b5X3Zalfkx9IWi3AXfwIicfR9IEJHY/0sqjCFg+Mij4Vm2ZbEaHEqZeJPYC0SggcgdnD4QceKIBgvE7D5X/Sf1CajMeQkahHGJXxB2ACeyVBDA7toJpuPTG180JgQjd/2ics2RiDMIo1MEZE6KHgQAgno2DiAxeMzQFVEgY4gwH+9O4lIOJPaZ5IQDQCf3tXyvuxHbCDsdIJ/G3G2AbI3hLF5vYdULjQ2BFoudWA1QmfA6OWm/ESgSLHMP7JtA5PeDePmXJbMA4+q1E/kEj2uD+yytUiCyvESgAGGw3JkobGzIPIZBHLGdQkPkKKp2cHquTNN+LhnHIjz0iEXGyQDNAKf+EbbbMSeGJ2bvxBZi+aM1JTGNx1FqT2r5X3YCMsm0JxJ+gh9SUvjIan86dYvJDXHzmnGEJWIKXt8OX3LktmHH7ridseVMnJDB9nifzo481bcSBoYlnI7GRTRBkk1lMFFHAIPR/kjFCHdiX8CaozCdv4AgQiIZj/AA7d8r7sFcc1goZwAEPto9JAMCHx4fcuS2YcfuuJ2x5UytP06OPNW3oLIoTZu/E1kdlzNQZrWmVTNATeA3rbO5fK+7AGECQGqDlIgU7HD7lyWzDj91xO2PKmVp+nRx5q29ApQTknWQmtdyTjs+5UddIYDmRsU2VAO5fK+7BBhiL1xIhRBY2Iys3S+uBnANMtUIceXjhxtXDh9y5LZhx+64nbHlTK0/To481bcTfiEIAJwRf3tyyjpwMm6eycE3Es/UDwgm7Z+oBcdwFwR275X3YJLCZAid/wn6JbAabBMIM63IfEC92zIuwTosNCwH0mYxD538yw4fcuS2YcfuuJ2x5UytP06OTNW3AgIAAck6IxMQhpfizIBxsjX0EAAGEAgAEEAgwIKMU4wVrfiLH5YzOdPX0gQQCC4PavlfdggACQYg6o3Ixn/wBAkmAoY2R9goLBfci5H5SdTkEEl+wAOfQGiZ4Ec8TGf1iJASCDl/JAQAIIfB9MBIBBB1/aEgBBBy/jEDCFi1/khLzFjm+HQJDAkvyRgAJMcPWBD2P8wdmfqaZ7EdiCLUABgBiVEQgQIRAAq+zNNQuAJM3aFQ9RCM3wiMcrWhgBgo/wncbMAIkYZgSIeuu+V92g59UtUIp2SQbXJBRKQNrAKc5mIfZz6AN2wSYsUxkUAAAAGAyGAyEWeIQbjVAAAADADTEWcNyyI9ELLph0A8AzEDghb9PBLenywe2FyyI+QhapYCHTmc4AiMwchEn2UQ4YoFxPwIOBB+yvX1W4w+HPXfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfK+8jfLOTPZTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRTFFMUUxRZyZ7L//2Q=="
    mediatype: "image/png"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - citrix.citrix.com
          resources:
          - citrix-adc-istio-ingress-gateways
          - citrix-adc-istio-ingress-gateways/status
          - citrix-adc-istio-ingress-gateways/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - autoscaling
          resources:
          - horizontalpodautoscalers
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          resourceNames:
          - privileged
          verbs:
          - use
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: citrix-adc-istio-ingress-gateway-operator-mgr
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:latest
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                - --leader-election-id=citrix-adc-istio-ingress-gateway-operator
                image: registry.connect.redhat.com/citrix/istioingressgateway:v0.9.5-v1beta
                name: manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          resourceNames:
          - privileged
          verbs:
          - use
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Citrix
  - ADC
  - Istio
  - Ingress
  links:
  - name: Citrix Adc Istio Ingress Gateway Operator
    url: https://citrix-adc-istio-ingress-gateway-operator.domain
  maintainers:
  - email: ajeetashakeet@citrix.com
    name: AjeetaShakeet
  maturity: alpha
  provider:
    name: citrix
  version: 0.9.5
