apiVersion: v2
appVersion: 1.11.0
description: A Helm chart to deploy resources which install Citrix ADC CPX in Istio
  Service Mesh as sidecar in application pod
home: https://www.citrix.com
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
kubeVersion: '>=v1.16.0-0'
maintainers:
- email: dhiraj.gedam@citrix.com
  name: dheerajng
- email: subash.dangol@citrix.com
  name: subashd
name: citrix-cpx-istio-sidecar-injector
sources:
- https://github.com/citrix/citrix-xds-adaptor
version: 1.11.0
