apiVersion: v1
appVersion: 1.6.4
description: A Helm chart to deploy resources which install Citrix ADC CPX in Istio Service Mesh as sidecar in application pod
home: https://www.citrix.com
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
maintainers:
- email: dhiraj.gedam@citrix.com
  name: dheerajng
- email: subash.dangol@citrix.com
  name: subashd
name: citrix-cpx-istio-sidecar-injector
sources:
- https://github.com/citrix/citrix-istio-adaptor
version: 1.6.4
