# Default values for cpx-istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

xDSAdaptor:
    image: quay.io/citrix/citrix-xds-adaptor:0.9.5
    imagePullPolicy: IfNotPresent
    proxyType: sidecar
    secureConnect: true

coe:
    coeURL:
 
istioPilot:
    name: istiod-basic
    namespace: istio-system
    secureGrpcPort: 15012
    insecureGrpcPort: 15010
    SAN: #"spiffe://cluster.local/ns/istio-system/sa/istiod-service-account"

certProvider:
    caAddr: istiod-basic.istio-system.svc
    caPort: 15012
    trustDomain: cluster.local
    certTTLinHours: 720
    clusterId: Kubernetes

cpxProxy:
    netscalerUrl: "http://127.0.0.1"
    image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-58.30
    imagePullPolicy: IfNotPresent
    EULA: NO
    cpxSidecarMode: YES
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    #licenseServerIP: this value is taken from ADMSettings.ADMIP

sidecarWebHook:
    webhookImage: gcr.io/istio-release/sidecar_injector:1.0.0
    imagePullPolicy: IfNotPresent

ADMSettings:
    ADMIP:
    ADMFingerPrint:
    licenseServerIP:
    licenseServerPort: 27000
    bandWidthLicense: false
    bandWidth:

webhook:
    injectionLabelName: cpx-injection

