apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: citrix-cpx-istio-sidecar-injectors.citrix.citrix.com
spec:
  group: citrix.citrix.com
  names:
    kind: Citrix-cpx-istio-sidecar-injector
    listKind: Citrix-cpx-istio-sidecar-injectorList
    plural: citrix-cpx-istio-sidecar-injectors
    singular: citrix-cpx-istio-sidecar-injector
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Citrix-cpx-istio-sidecar-injector is the Schema for the citrix-cpx-istio-sidecar-injectors API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Spec defines the desired state of Citrix-cpx-istio-sidecar-injector
          type: object
          x-kubernetes-preserve-unknown-fields: true
        status:
          description: Status defines the observed state of Citrix-cpx-istio-sidecar-injector
          type: object
          x-kubernetes-preserve-unknown-fields: true
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
