# permissions for end users to view citrix-cpx-istio-sidecar-injectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: citrix-cpx-istio-sidecar-injector-viewer-role
rules:
- apiGroups:
  - citrix.citrix.com
  resources:
  - citrix-cpx-istio-sidecar-injectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - citrix.citrix.com
  resources:
  - citrix-cpx-istio-sidecar-injectors/status
  verbs:
  - get
